<?php $collection = $this->_getCollection(); ?>
<?php if (count($collection) > 0) : ?>
<div class="ibanner ibanner-content-top">
<?php foreach ($collection as $item) : ?>
	<?php $_imageList = $item->getImageList(); ?>
    <?php if (is_array($_imageList) and sizeof($_imageList) > 0) : ?>
    <div class="pikachoose">
        <ul class="ibanner-slider-top jcarousel-skin-pika" style="display:none">
        <?php foreach ($_imageList as &$_item) : ?>
            <li><a href="<?php echo $_item['label']; ?>"><img src="<?php echo $this->helper('ibanner/image')->init($_item['file'])->resize(675,216); ?>" alt=""/></a></li>
        <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
<?php endforeach; ?>
</div>
<script language="javascript">
<!--
jQuery(document).ready(
    function (){
        if (jQuery(".ibanner-slider-top").length > 0) {
            jQuery(".ibanner-slider-top").PikaChoose();
        }
    });
-->
</script>
<div style="clear:both;"></div>
<?php endif; ?>